In [ ]:
 #IMPLEMENTING SVR

In [ ]:
import pandas as pd 
import os
from scipy import stats
import numpy as np
import matplotlib.pyplot as plt
import random
path_data = "/content/drive/My Drive/ICIP/"
path_imgs = "/content/drive/My Drive/ICIP/train_imgs/"

In [ ]:
#TEST DATA
test_path_data="/content/drive/My Drive/ICIP/TEST/"

In [ ]:
# Load data from csv
# img_info1 = pd.read_csv(path_data+'img_info1.csv')
# headers = pd.read_csv(path_data+'headers_TRAIN.csv')
# users = pd.read_csv(path_data+'users_TRAIN.csv')
popularity = pd.read_csv(path_data+'popularity_TRAIN.csv')  #Actually contains the number of views over time
Train_features=pd.read_csv(path_data+'Train_features.csv') #Contains the training features
Test_features=pd.read_csv(path_data+'Test_features.csv') #Contains the test features

In [ ]:
#PREDICTION DATA
Predict_features=pd.read_csv(test_path_data+'Predict_features.csv') 

In [ ]:
#Storing the max views
popularity.sort_values(by=['FlickrId'],inplace=True)

In [ ]:
popularity.head()

Unnamed: 0     FlickrId      Day01  ...  Day28  Day29       Day30
0           0  23647573678   4.587202  ...   18.0   18.0   18.000000
1           1  23647582078   1.850177  ...    9.0    9.0    9.000000
2           2  23647582388   0.926886  ...   11.0   11.0   11.000000
3           3  23647583748   0.000000  ...   11.0   11.0   12.048102
4           4  23647586378  80.401242  ...  121.0  121.0  121.000000

[5 rows x 32 columns]

In [ ]:
#selecting the data
max_views=popularity[['FlickrId','Day30']].values
# img_views=img_views[:,1:]
max_views.shape

(20337, 2)

In [ ]:
max_views=pd.DataFrame(max_views,columns=['FlickrId','Views'])

In [ ]:
max_views

FlickrId       Views
0      2.364757e+10   18.000000
1      2.364758e+10    9.000000
2      2.364758e+10   11.000000
3      2.364758e+10   12.048102
4      2.364759e+10  121.000000
...             ...         ...
20332  4.910893e+10   67.300129
20333  4.910893e+10   18.000000
20334  4.910893e+10    1.000000
20335  4.910893e+10    1.000000
20336  4.910893e+10  532.225155

[20337 rows x 2 columns]

In [ ]:
Train_features['FlickrId']=Train_features['0']

In [ ]:
Train_features.drop(['0'],axis=1,inplace=True)

In [ ]:
Train_features.sort_values(by='FlickrId',inplace=True)

In [ ]:
Train_features

1    2      3         4  ...  2245  2246  2247      FlickrId
9087   0.0  1.0  148.0    7006.0  ...   0.0   0.0   0.0  2.364757e+10
461    0.0  0.0   55.0     565.0  ...   0.0   0.0   0.0  2.364758e+10
7361   1.0  1.0    3.0   16203.0  ...   0.0   0.0   0.0  2.364758e+10
10157  0.0  0.0  485.0     397.0  ...   0.0   0.0   0.0  2.364759e+10
7888   0.0  0.0    1.0   19380.0  ...   0.0   0.0   0.0  2.364759e+10
...    ...  ...    ...       ...  ...   ...   ...   ...           ...
397    0.0  0.0    0.0     116.0  ...   0.0   0.0   0.0  4.910893e+10
1201   0.0  0.0    5.0     595.0  ...   0.0   0.0   0.0  4.910893e+10
5909   1.0  1.0    0.0  339486.0  ...   0.0   0.0   0.0  4.910893e+10
14904  0.0  0.0    0.0     245.0  ...   0.0   0.0   0.0  4.910893e+10
16153  1.0  1.0   25.0     168.0  ...   0.0   0.0   0.0  4.910893e+10

[18303 rows x 2248 columns]

In [ ]:
Test_features['FlickrId']=Test_features['0']

In [ ]:
Test_features.drop(['0'],axis=1,inplace=True)

In [ ]:
Test_features.sort_values(by='FlickrId',inplace=True)

In [ ]:
Test_features

1    2      3        4  ...  2245  2246  2247      FlickrId
435   0.0  0.0    5.0    562.0  ...   0.0   0.0   0.0  2.364758e+10
1649  0.0  0.0    1.0     69.0  ...   0.0   0.0   0.0  2.364759e+10
1630  0.0  1.0  216.0    575.0  ...   0.0   0.0   0.0  2.364760e+10
1399  1.0  1.0   96.0  11796.0  ...   0.0   0.0   0.0  2.364761e+10
818   0.0  0.0  502.0    629.0  ...   0.0   0.0   0.0  2.364765e+10
...   ...  ...    ...      ...  ...   ...   ...   ...           ...
1145  0.0  0.0    0.0     60.0  ...   0.0   0.0   0.0  4.910871e+10
1960  1.0  1.0  410.0   3430.0  ...   0.0   0.0   0.0  4.910875e+10
1265  0.0  0.0    0.0    734.0  ...   0.0   0.0   0.0  4.910878e+10
1373  1.0  1.0   62.0   7181.0  ...   0.0   0.0   0.0  4.910883e+10
309   0.0  0.0    2.0     85.0  ...   0.0   0.0   0.0  4.910888e+10

[2034 rows x 2248 columns]

In [ ]:
Predict_features['FlickrId']=Predict_features['0']

In [ ]:
Predict_features.drop(['0'],axis=1,inplace=True)

In [ ]:
Predict_features.sort_values(by='FlickrId',inplace=True)

In [ ]:
Predict_features

1    2       3       4  ...  2245  2246  2247      FlickrId
0     1.0  1.0     1.0  4645.0  ...   0.0   0.0   0.0  4.909858e+10
1     0.0  0.0   269.0    65.0  ...   0.0   0.0   0.0  4.909858e+10
2     1.0  1.0  1077.0  6338.0  ...   0.0   0.0   0.0  4.909858e+10
3     1.0  1.0   101.0  1897.0  ...   0.0   0.0   0.0  4.909858e+10
4     0.0  0.0     0.0   273.0  ...   0.0   0.0   0.0  4.909858e+10
...   ...  ...     ...     ...  ...   ...   ...   ...           ...
7688  0.0  0.0     0.0   204.0  ...   0.0   0.0   0.0  4.910454e+10
7689  0.0  0.0   136.0    15.0  ...   0.0   0.0   0.0  4.910454e+10
7690  0.0  0.0     2.0    41.0  ...   0.0   0.0   0.0  4.910454e+10
7691  1.0  1.0    18.0  7957.0  ...   0.0   0.0   0.0  4.910455e+10
7692  0.0  0.0     0.0   199.0  ...   0.0   0.0   0.0  4.910455e+10

[7693 rows x 2248 columns]

In [ ]:
Train_SVR=pd.merge(max_views,Train_features,on='FlickrId')

In [ ]:
max_views

FlickrId       Views
0      2.364757e+10   18.000000
1      2.364758e+10    9.000000
2      2.364758e+10   11.000000
3      2.364758e+10   12.048102
4      2.364759e+10  121.000000
...             ...         ...
20332  4.910893e+10   67.300129
20333  4.910893e+10   18.000000
20334  4.910893e+10    1.000000
20335  4.910893e+10    1.000000
20336  4.910893e+10  532.225155

[20337 rows x 2 columns]

In [ ]:
Train_SVR

FlickrId       Views    1    2      3  ...  2243  2244  2245  2246  2247
0      2.364757e+10   18.000000  0.0  1.0  148.0  ...   0.0   0.0   0.0   0.0   0.0
1      2.364758e+10    9.000000  0.0  0.0   55.0  ...   0.0   0.0   0.0   0.0   0.0
2      2.364758e+10   12.048102  1.0  1.0    3.0  ...   0.0   0.0   0.0   0.0   0.0
3      2.364759e+10  121.000000  0.0  0.0  485.0  ...   0.0   0.0   0.0   0.0   0.0
4      2.364759e+10  228.000000  0.0  0.0    1.0  ...   0.0   0.0   0.0   0.0   0.0
...             ...         ...  ...  ...    ...  ...   ...   ...   ...   ...   ...
18298  4.910893e+10   67.300129  0.0  0.0    0.0  ...   0.0   0.0   0.0   0.0   0.0
18299  4.910893e+10   18.000000  0.0  0.0    5.0  ...   0.0   0.0   0.0   0.0   0.0
18300  4.910893e+10    1.000000  1.0  1.0    0.0  ...   0.0   0.0   0.0   0.0   0.0
18301  4.910893e+10    1.000000  0.0  0.0    0.0  ...   0.0   0.0   0.0   0.0   0.0
18302  4.910893e+10  532.225155  1.0  1.0   25.0  ...   0.0   0.0   0.0   0.0   0.0

[18303 rows x 2249 columns]

In [ ]:
Test_SVR=pd.merge(max_views,Test_features,on='FlickrId')

In [ ]:
Test_SVR

FlickrId       Views    1    2      3  ...  2243  2244  2245  2246  2247
0     2.364758e+10   11.000000  0.0  0.0    5.0  ...   0.0   0.0   0.0   0.0   0.0
1     2.364759e+10    6.000000  0.0  0.0    1.0  ...   0.0   0.0   0.0   0.0   0.0
2     2.364760e+10  446.337212  0.0  1.0  216.0  ...   0.0   0.0   0.0   0.0   0.0
3     2.364761e+10   29.000000  1.0  1.0   96.0  ...   0.0   0.0   0.0   0.0   0.0
4     2.364765e+10  217.000000  0.0  0.0  502.0  ...   0.0   0.0   0.0   0.0   0.0
...            ...         ...  ...  ...    ...  ...   ...   ...   ...   ...   ...
2029  4.910871e+10  227.289598  0.0  0.0    0.0  ...   0.0   0.0   0.0   0.0   0.0
2030  4.910875e+10  149.000000  1.0  1.0  410.0  ...   0.0   0.0   0.0   0.0   0.0
2031  4.910878e+10    1.000000  0.0  0.0    0.0  ...   0.0   0.0   0.0   0.0   0.0
2032  4.910883e+10   10.000000  1.0  1.0   62.0  ...   0.0   0.0   0.0   0.0   0.0
2033  4.910888e+10    1.000000  0.0  0.0    2.0  ...   0.0   0.0   0.0   0.0   0.0

[2034 rows x 2249 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

In [ ]:
#TRAINING DATA
X=Train_SVR[['5','3','6','7','8']].values
print(X.shape)

(18303, 5)


In [ ]:
X[0,:]

array([ 21.11433057, 148.        , 153.        ,   0.        ,
         0.        ,   0.        ])

In [ ]:
#Labels
Y=Train_SVR.values
Y=Y[:,1]
print(Y.shape)
print(Y)

(18303,)
[ 18.           9.          12.04810165 ...   1.           1.
 532.22515532]


In [ ]:
#Reshape
Y=Y.reshape((Y.shape[0],1))

In [ ]:
#Scaling
sc_X = StandardScaler()
sc_y = StandardScaler()
Train_X = sc_X.fit_transform(X)
Train_Y = sc_y.fit_transform(Y)

In [ ]:
Train_Y=Train_Y.reshape((Train_Y.shape[0],))

In [ ]:
Train_Y

array([-0.1166267 , -0.12225793, -0.12035076, ..., -0.12726347,
       -0.12726347,  0.20512025])

In [ ]:
regressor = SVR(kernel='rbf',epsilon=0.001)
regressor.fit(Train_X,Train_Y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.001, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
#The test data
Test_X=Test_SVR[['FlickrId','5','3','6','7','8']].values
Test_Y=Test_SVR[['Views']].values

In [ ]:
Test_X.shape

(2034, 4)

In [ ]:
Test_Y

array([[ 29.        ],
       [ 14.        ],
       [227.        ],
       ...,
       [  5.        ],
       [ 43.        ],
       [413.29423312]])

In [ ]:
#PREDICTION
y_pred = sc_y.inverse_transform (regressor.predict (sc_X.transform(Test_X[:,1:])))

In [ ]:
sc_X.transform(Test_X)

array([[-0.10284126, -0.146983  , -0.2982077 ],
       [-0.10284126, -0.14886105, -0.2982077 ],
       [-0.10201184, -0.14936353, -0.2982077 ],
       ...,
       [ 0.68759462,  0.10056427,  0.24329222],
       [-0.10325597, -0.1493541 , -0.2982077 ],
       [ 0.00830082, -0.03437846,  0.33746612]])

In [ ]:
y_pred

array([ 27.79997739,   4.18082076, 625.4765043 , ...,   4.2488312 ,
        11.44373827,   3.49776845])

In [ ]:
Test_Y

array([[ 11.        ],
       [  6.        ],
       [446.33721213],
       ...,
       [  1.        ],
       [ 10.        ],
       [  1.        ]])

In [ ]:
# y_pred=y_pred.reshape((y_pred.shape[0],1))

In [ ]:
# y_pred

array([[113.05699287],
       [127.96322579],
       [130.3491505 ],
       ...,
       [112.72010515],
       [129.44439317],
       [137.07498652]])

In [ ]:
Test_Y=Test_Y.reshape((Test_Y.shape[0],))

In [ ]:
Test_Y.shape

(2034,)

In [ ]:
clusters_rank=pd.DataFrame(y_pred,columns=['Predicted'])
clusters_rank.insert(1,"Actual",Test_Y)

In [ ]:
clusters_rank

Predicted      Actual
0      27.906303   11.000000
1       4.501963    6.000000
2     745.057526  446.337212
3     110.156072   29.000000
4     129.328084  217.000000
...          ...         ...
2029   15.989625  227.289598
2030  112.146870  149.000000
2031    4.580456    1.000000
2032   11.692963   10.000000
2033    3.814659    1.000000

[2034 rows x 2 columns]

In [ ]:
clusters_rank.corr(method='spearman')

Predicted    Actual
Predicted   1.000000  0.744021
Actual      0.744021  1.000000

In [ ]:
#Predicting the 30 day sequence

In [ ]:
Test_Shape=pd.read_csv(path_data+'Test_Shape_Data.csv')

In [ ]:
Test_Shape.sort_values(by='FlickrId',inplace=True)

In [ ]:
Test_Shape

FlickrId  Cluster        0  ...        27        28   29
321   2.364758e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
1216  2.364759e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
1201  2.364760e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
1971  2.364761e+10     32.0  0.00000  ...  1.000000  1.000000  1.0
604   2.364765e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
...            ...      ...      ...  ...       ...       ...  ...
835   4.910871e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
1454  4.910875e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
928   4.910878e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
1009  4.910883e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
226   4.910888e+10      0.0  0.40454  ...  0.990879  0.995408  1.0

[2034 rows x 32 columns]

In [ ]:
clusters_rank['FlickrId']=Test_X[:,0]

In [ ]:
clusters_rank

Predicted      Actual      FlickrId
0       85.478694   29.000000  2.364761e+10
1        5.635284   14.000000  2.364766e+10
2       19.844803  227.000000  2.364773e+10
3       78.175823  211.000000  2.364776e+10
4        6.863920    3.000000  2.364781e+10
...           ...         ...           ...
2029  2424.662524  168.000000  4.910871e+10
2030    64.375029    7.000000  4.910871e+10
2031     7.089707    5.000000  4.910873e+10
2032    93.059656   43.000000  4.910890e+10
2033   288.687313  413.294233  4.910891e+10

[2034 rows x 3 columns]

In [ ]:
clusters_rank.drop(['Actual'],axis=1,inplace=True)

In [ ]:
Predicted_Seq=pd.merge(Test_Shape,clusters_rank,on='FlickrId')

In [ ]:
Predicted_Seq

FlickrId  Cluster        0  ...        28   29   Predicted
0     2.364758e+10      0.0  0.40454  ...  0.995408  1.0   27.906303
1     2.364759e+10      0.0  0.40454  ...  0.995408  1.0    4.501963
2     2.364760e+10      0.0  0.40454  ...  0.995408  1.0  745.057526
3     2.364761e+10     32.0  0.00000  ...  1.000000  1.0  110.156072
4     2.364765e+10      0.0  0.40454  ...  0.995408  1.0  129.328084
...            ...      ...      ...  ...       ...  ...         ...
2029  4.910871e+10      0.0  0.40454  ...  0.995408  1.0   15.989625
2030  4.910875e+10      0.0  0.40454  ...  0.995408  1.0  112.146870
2031  4.910878e+10      0.0  0.40454  ...  0.995408  1.0    4.580456
2032  4.910883e+10      0.0  0.40454  ...  0.995408  1.0   11.692963
2033  4.910888e+10      0.0  0.40454  ...  0.995408  1.0    3.814659

[2034 rows x 33 columns]

In [ ]:
Predicted_Seq.drop(['Cluster'],axis=1,inplace=True)

In [ ]:
Predicted_Seq_np=Predicted_Seq.values

In [ ]:
Predicted_Seq_np.shape

(2034, 32)

In [ ]:
for i in range(Predicted_Seq_np.shape[0]):
  views=Predicted_Seq_np[i,31]
  for j in range(1,Predicted_Seq_np.shape[1]-1):
    Predicted_Seq_np[i,j]*=views

In [ ]:
Predicted_Seq_np[0,:]

array([2.36475824e+10, 1.12461924e+01, 1.52903775e+01, 1.74994795e+01,
       1.89590614e+01, 2.00428522e+01, 2.08198813e+01, 2.14862832e+01,
       2.20934390e+01, 2.26437154e+01, 2.31280458e+01, 2.35704382e+01,
       2.39894088e+01, 2.43510708e+01, 2.46820492e+01, 2.49785476e+01,
       2.52765317e+01, 2.55550402e+01, 2.58018004e+01, 2.60375141e+01,
       2.62569392e+01, 2.64541630e+01, 2.66376029e+01, 2.68185349e+01,
       2.69821868e+01, 2.71366187e+01, 2.72849790e+01, 2.74138952e+01,
       2.75464033e+01, 2.76723253e+01, 2.77999774e+01, 2.77999774e+01])

In [ ]:
Predicted_Seq=pd.DataFrame(Predicted_Seq_np)

In [ ]:
Predicted_Seq

0           1           2   ...          29          30          31
0     2.364758e+10   11.246192   15.290378  ...   27.672325   27.799977   27.799977
1     2.364759e+10    1.691308    2.299510  ...    4.161623    4.180821    4.180821
2     2.364760e+10  253.030030  344.020851  ...  622.604439  625.476504  625.476504
3     2.364761e+10    0.000000    0.000000  ...   51.273496   51.273496   51.273496
4     2.364765e+10   96.545650  131.263931  ...  237.559747  238.655607  238.655607
...            ...         ...         ...  ...         ...         ...         ...
2029  4.910871e+10    6.375066    8.667570  ...   15.686455   15.758817   15.758817
2030  4.910875e+10   33.696921   45.814496  ...   82.914477   83.296960   83.296960
2031  4.910878e+10    1.718821    2.336917  ...    4.229321    4.248831    4.248831
2032  4.910883e+10    4.629446    6.294217  ...   11.391191   11.443738   11.443738
2033  4.910888e+10    1.414986    1.923822  ...    3.481707    3.497768    3.497768

[2034 rows x 32 columns]

In [ ]:
Predicted_Seq.drop([31],axis=1,inplace=True)

In [ ]:
#Renaming all the columns:
Predicted_Seq.rename({0:'FlickrId',1: 'Day01',2: 'Day02', 3:'Day03',4:'Day04',5:'Day05',6:'Day06',7:'Day07',8:'Day08',9:'Day09',10:'Day10',11:'Day11',12:'Day12',13:'Day13',14:'Day14',15:'Day15',16:'Day16',17:'Day17',18:'Day18',19:'Day19',20:'Day20',21:'Day21',22:'Day22',23:'Day23',24:'Day24',25:'Day25',26:'Day26',27:'Day27',28:'Day28',29:'Day29',30:'Day30'},axis=1,inplace=True)

In [ ]:
Predicted_Seq.FlickrId=Predicted_Seq.FlickrId.astype(int)

In [ ]:
Predicted_Seq.to_csv(path_data+'Predictions.csv',index=False)

In [ ]:
#FOR THE PREDICTION DATA

In [ ]:
Predict_X=Predict_features[['FlickrId','5','3','6','7','8']].values

In [ ]:
Predict_X.shape

(7693, 7)

In [ ]:
Predcited_Scale = sc_y.inverse_transform (regressor.predict (sc_X.transform(Predict_X[:,1:])))

In [ ]:
Predcited_Scale

array([  53.52291853,  432.54010771, 1189.09300318, ...,    3.00461999,
         15.81003777,    3.54345342])

In [ ]:
Predictions=pd.DataFrame(Predcited_Scale,columns=['Predicted'])

In [ ]:
Predictions.insert(1,'FlickrId',Predict_X[:,0])

In [ ]:
Predictions

Predicted      FlickrId
0       53.522919  4.909858e+10
1      432.540108  4.909858e+10
2     1189.093003  4.909858e+10
3      755.249459  4.909858e+10
4        5.331484  4.909858e+10
...           ...           ...
7688    27.113991  4.910454e+10
7689    96.718921  4.910454e+10
7690     3.004620  4.910454e+10
7691    15.810038  4.910455e+10
7692     3.543453  4.910455e+10

[7693 rows x 2 columns]

In [ ]:
#Reading the shapes of the images
Predict_Shape=pd.read_csv(test_path_data+'Predicted_Shape_Data.csv')

In [ ]:
Predict_Shape.sort_values(by='FlickrId',inplace=True)

In [ ]:
Predict_Shape

FlickrId  Cluster         0  ...        27        28   29
0     4.909858e+10      0.0  0.404540  ...  0.990879  0.995408  1.0
1     4.909858e+10      0.0  0.404540  ...  0.990879  0.995408  1.0
2     4.909858e+10      0.0  0.404540  ...  0.990879  0.995408  1.0
3     4.909858e+10      0.0  0.404540  ...  0.990879  0.995408  1.0
6169  4.909858e+10     32.0  0.000000  ...  1.000000  1.000000  1.0
...            ...      ...       ...  ...       ...       ...  ...
6166  4.910454e+10      0.0  0.404540  ...  0.990879  0.995408  1.0
6167  4.910454e+10      0.0  0.404540  ...  0.990879  0.995408  1.0
7454  4.910454e+10      1.0  0.755823  ...  0.998732  0.999293  1.0
6168  4.910455e+10      0.0  0.404540  ...  0.990879  0.995408  1.0
7455  4.910455e+10      1.0  0.755823  ...  0.998732  0.999293  1.0

[7693 rows x 32 columns]

In [ ]:
Images_popularity=pd.merge(Predict_Shape,Predictions,on='FlickrId')

In [ ]:
Images_popularity

FlickrId  Cluster         0  ...        28   29    Predicted
0     4.909858e+10      0.0  0.404540  ...  0.995408  1.0    50.841308
1     4.909858e+10      0.0  0.404540  ...  0.995408  1.0   452.082318
2     4.909858e+10      0.0  0.404540  ...  0.995408  1.0  1517.937187
3     4.909858e+10      0.0  0.404540  ...  0.995408  1.0   770.222493
4     4.909858e+10     32.0  0.000000  ...  1.000000  1.0     5.198677
...            ...      ...       ...  ...       ...  ...          ...
7688  4.910454e+10      0.0  0.404540  ...  0.995408  1.0    25.866718
7689  4.910454e+10      0.0  0.404540  ...  0.995408  1.0   124.749548
7690  4.910454e+10      1.0  0.755823  ...  0.999293  1.0     2.960678
7691  4.910455e+10      0.0  0.404540  ...  0.995408  1.0    14.980216
7692  4.910455e+10      1.0  0.755823  ...  0.999293  1.0     3.499277

[7693 rows x 33 columns]

In [ ]:
Images_popularity.drop(['Cluster'],axis=1,inplace=True)

In [ ]:
Images_popularity_np=Images_popularity.values

In [ ]:
Images_popularity_np.shape

(7693, 32)

In [ ]:
for i in range(Images_popularity_np.shape[0]):
  views=Images_popularity_np[i,31]
  for j in range(1,Images_popularity_np.shape[1]-1):
    Images_popularity_np[i,j]*=views

In [ ]:
Images_popularity_np[0,:]

array([4.90985818e+10, 2.16521414e+01, 2.94383560e+01, 3.36915099e+01,
       3.65016232e+01, 3.85882309e+01, 4.00842344e+01, 4.13672490e+01,
       4.25361978e+01, 4.35956374e+01, 4.45281122e+01, 4.53798443e+01,
       4.61864826e+01, 4.68827855e+01, 4.75200138e+01, 4.80908581e+01,
       4.86645629e+01, 4.92007715e+01, 4.96758556e+01, 5.01296720e+01,
       5.05521281e+01, 5.09318403e+01, 5.12850147e+01, 5.16333607e+01,
       5.19484375e+01, 5.22457631e+01, 5.25313992e+01, 5.27795997e+01,
       5.30347158e+01, 5.32771518e+01, 5.35229185e+01, 5.35229185e+01])

In [ ]:
Images_popularity=pd.DataFrame(Images_popularity_np)

In [ ]:
Images_popularity

0           1           2   ...          29          30          31
0     4.909858e+10   21.685792   29.484108  ...   53.359953   53.606102   53.606102
1     4.909858e+10  143.786654  195.493029  ...  353.800728  355.432806  355.432806
2     4.909858e+10  280.422038  381.263157  ...  690.005077  693.188061  693.188061
3     4.909858e+10  329.477430  447.959104  ...  810.710531  814.450328  814.450328
4     4.909858e+10    0.000000    0.000000  ...    5.652320    5.652320    5.652320
...            ...         ...         ...  ...         ...         ...         ...
7688  4.910454e+10   11.033347   15.000992  ...   27.148598   27.273835   27.273835
7689  4.910454e+10   43.588619   59.263297  ...  107.253940  107.748701  107.748701
7690  4.910454e+10    2.514288    2.890586  ...    3.324207    3.326557    3.326557
7691  4.910455e+10    6.413249    8.719485  ...   15.780410   15.853205   15.853205
7692  4.910455e+10    2.934299    3.373457  ...    3.879515    3.882257    3.882257

[7693 rows x 32 columns]

In [ ]:
Images_popularity.drop([31],axis=1,inplace=True)

In [ ]:
#Renaming all the columns:
Images_popularity.rename({0:'FlickrId',1: 'Day01',2: 'Day02', 3:'Day03',4:'Day04',5:'Day05',6:'Day06',7:'Day07',8:'Day08',9:'Day09',10:'Day10',11:'Day11',12:'Day12',13:'Day13',14:'Day14',15:'Day15',16:'Day16',17:'Day17',18:'Day18',19:'Day19',20:'Day20',21:'Day21',22:'Day22',23:'Day23',24:'Day24',25:'Day25',26:'Day26',27:'Day27',28:'Day28',29:'Day29',30:'Day30'},axis=1,inplace=True)

In [ ]:
Images_popularity.FlickrId=Images_popularity.FlickrId.astype(int)

In [ ]:
Images_popularity.to_csv(test_path_data+'predicted_popularity_test.csv',index=False)