In [ ]:
import pandas as pd 
import os
from scipy import stats
import numpy as np
import matplotlib.pyplot as plt
import random
path_data = "/content/drive/My Drive/ICIP/"
path_imgs = "/content/drive/My Drive/ICIP/train_imgs/"

In [ ]:
#TEST DATA
test_path_data="/content/drive/My Drive/ICIP/TEST/"

In [ ]:
# Numerical=pd.read_csv(path_data+'Numerical_features_and_cluster.csv')
# Y=pd.read_csv(path_data+'Clusters.csv')
features=pd.read_csv(path_data+'Features.csv') #Numerical features and clusters
seq_shape=pd.read_csv(path_data+'Optimal.csv') #Conatins the shapes of prototype clusters
Text_features=pd.read_csv(path_data+'textfeatures.csv')

In [ ]:
test_features=pd.read_csv(test_path_data+'test_features.csv') #Test numerical features
test_text_features=pd.read_csv(test_path_data+'test_textfeatures.csv') #Test text features

In [ ]:
features

FlickrId  Ispro  HasStats  ...  AvgGroupsMemb  AvgGroupPhotos  Cluster
0      23647573678      0         1  ...       0.000000        0.000000       36
1      23647582078      0         0  ...       0.000000        0.000000       38
2      23647582388      0         0  ...       0.000000        0.000000       40
3      23647583748      1         1  ...       0.000000        0.000000       40
4      23647586378      0         0  ...       0.000000        0.000000        0
...            ...    ...       ...  ...            ...             ...      ...
20332  49108928407      0         0  ...       0.000000        0.000000       40
20333  49108930512      0         0  ...       0.000000        0.000000       33
20334  49108933202      1         1  ...       0.000000        0.000000        5
20335  49108933542      0         0  ...       0.000000        0.000000       45
20336  49108934937      1         1  ...   11083.090909   908502.909091        8

[20337 rows x 15 columns]

In [ ]:
test_features

FlickrId  Ispro  HasStats  ...  NumGroups  AvgGroupsMemb  AvgGroupPhotos
0     49098581833      1         1  ...          0       0.000000    0.000000e+00
1     49098582593      0         0  ...          3     456.000000    1.217800e+04
2     49098582698      1         1  ...         69   41385.347826    2.480120e+06
3     49098582733      1         1  ...          4    2458.250000    7.432825e+04
4     49098584118      0         0  ...          0       0.000000    0.000000e+00
...           ...    ...       ...  ...        ...            ...             ...
7688  49104539732      0         0  ...          0       0.000000    0.000000e+00
7689  49104542697      0         0  ...          6    9716.000000    6.995257e+05
7690  49104544567      0         0  ...          0       0.000000    0.000000e+00
7691  49104545392      1         1  ...          0       0.000000    0.000000e+00
7692  49104546122      0         0  ...          0       0.000000    0.000000e+00

[7693 rows x 14 columns]

In [ ]:
features.Cluster.unique()

array([ 0, 38,  1,  3, 10, 26, 32, 13, 29, 41, 31,  2, 23,  8, 34, 22,  7,
       16, 46,  9, 28, 15, 33, 19,  6, 44,  5,  4, 18, 39, 40, 25, 17, 37,
       20, 12, 27, 11, 30, 35, 21, 14, 24, 43, 42, 36, 45, 47, 48])

In [ ]:
X=features.values
Y=X[:,-1]
X=X[:,:14]

In [ ]:
print(X.shape,Y.shape)

(20337, 14) (20337,)


In [ ]:
X[0,:]

array([2.36475737e+10, 0.00000000e+00, 1.00000000e+00, 1.48000000e+02,
       7.00600000e+03, 2.11143306e+01, 1.53000000e+02, 1.79549150e+04,
       3.28481451e+05, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00])

In [ ]:
Text_features

FlickrId  ...                                         Tags_lemma
0      23647573678  ...                                    ifttt instagram
1      23647582078  ...                                    ifttt instagram
2      23647582388  ...                                          instagram
3      23647583748  ...  clothing textile museum aeshm alice amd mary g...
4      23647586378  ...                                    ifttt instagram
...            ...  ...                                                ...
20332  49108928407  ...  phim u1ea3nh chu00faa u0111u1ee9c phu1eadt vu0...
20333  49108930512  ...                                    ifttt instagram
20334  49108933202  ...                                2019 2020 wikipedia
20335  49108933542  ...                                       admin review
20336  49108934937  ...  tacoma tideflats portoftacoma commencementbay ...

[20337 rows x 4 columns]

In [ ]:
Text_features.Title_lemma.fillna('photo',inplace=True)
Text_features.Description_lemma.fillna(' ',inplace=True)
Text_features.Tags_lemma.fillna(' ',inplace=True)

In [ ]:
test_text_features

FlickrId  ...                                         Tags_lemma
0     49098581833  ...             prf clariantinternationalltd clapr1634
1     49098582593  ...                                            carwash
2     49098582698  ...                                    ifttt instagram
3     49098582733  ...  greenheron usa wildlife butoridesvirescens u l...
4     49098584118  ...                                    ifttt instagram
...           ...  ...                                                ...
7688  49104539732  ...  volleyball mug lover like funny gift idea hobb...
7689  49104542697  ...                                    ifttt instagram
7690  49104544567  ...                                    ifttt instagram
7691  49104545392  ...                                    ifttt instagram
7692  49104546122  ...                                    ifttt instagram

[7693 rows x 4 columns]

In [ ]:
test_text_features.Title_lemma.fillna('photo',inplace=True)
test_text_features.Description_lemma.fillna(' ',inplace=True)
test_text_features.Tags_lemma.fillna(' ',inplace=True)

In [ ]:
test_text_features.isnull().sum()

FlickrId             0
Title_lemma          0
Description_lemma    0
Tags_lemma           0
dtype: int64

In [ ]:
#Checking for word counts

In [ ]:
from collections import Counter
count=Counter()

In [ ]:
for text in Text_features["Tags_lemma"].values:
    for word in text.split():
        count[word] += 1

In [ ]:
#Title
count.most_common() 

[('untitled', 3316),
 ('photo', 1063),
 ('de', 973),
 ('2017', 531),
 ('day', 438),
 ('la', 438),
 ('new', 393),
 ('2019', 366),
 ('love', 342),
 ('quote', 288),
 ('en', 249),
 ('get', 230),
 ('october', 220),
 ('time', 207),
 ('look', 198),
 ('like', 195),
 ('one', 195),
 ('1', 194),
 ('2', 189),
 ('photography', 183),
 ('go', 179),
 ('u', 178),
 ('night', 177),
 ('light', 177),
 ('fall', 173),
 ('e', 167),
 ('5', 162),
 ('make', 160),
 ('best', 160),
 ('sunset', 159),
 ('3', 156),
 ('el', 155),
 ('art', 155),
 ('life', 151),
 ('morning', 150),
 ('today', 143),
 ('street', 143),
 ('november', 141),
 ('work', 140),
 ('beautiful', 139),
 ('home', 139),
 ('good', 138),
 ('le', 138),
 ('black', 138),
 ('red', 133),
 ('add', 129),
 ('un', 129),
 ('happy', 128),
 ('autumn', 127),
 ('park', 127),
 ('take', 126),
 ('color', 124),
 ('7', 120),
 ('friday', 117),
 ('design', 116),
 ('see', 115),
 ('city', 114),
 ('del', 114),
 ('que', 113),
 ('come', 111),
 ('via', 111),
 ('dress', 111),
 ('l', 

In [ ]:
#Tags
count.most_common() 

[('ifttt', 20086),
 ('instagram', 19928),
 ('secondlife', 517),
 ('firestorm', 446),
 ('iphoneography', 386),
 ('square', 378),
 ('squareformat', 374),
 ('instagramapp', 370),
 ('uploadedbyinstagram', 367),
 ('nature', 320),
 ('landscape', 218),
 ('bird', 194),
 ('tree', 187),
 ('photo', 184),
 ('travel', 182),
 ('2019', 182),
 ('autumn', 165),
 ('sky', 159),
 ('2017', 155),
 ('street', 155),
 ('nikon', 152),
 ('photography', 150),
 ('people', 149),
 ('blackandwhite', 147),
 ('water', 143),
 ('cloud', 138),
 ('sunset', 135),
 ('art', 135),
 ('streetphotography', 129),
 ('portrait', 128),
 ('outdoor', 125),
 ('unitedstates', 117),
 ('city', 117),
 ('fall', 113),
 ('life', 113),
 ('flower', 112),
 ('bw', 112),
 ('canon', 106),
 ('light', 99),
 ('io', 98),
 ('architecture', 98),
 ('monochrome', 97),
 ('sea', 96),
 ('wildlife', 94),
 ('usa', 94),
 ('california', 93),
 ('beach', 93),
 ('outdoors', 90),
 ('urban', 90),
 ('color', 89),
 ('animal', 88),
 ('love', 87),
 ('u', 87),
 ('canada', 8

In [ ]:
#Description
count.most_common() 

[('href', 9551),
 ('rel', 9493),
 ('nofollow', 9492),
 ('noreferrer', 4319),
 ('via', 2816),
 ('instagram', 2485),
 ('de', 1028),
 ('và', 875),
 ('có', 801),
 ('view', 739),
 ('8211', 693),
 ('là', 624),
 ('các', 618),
 ('của', 610),
 ('la', 601),
 ('bạn', 584),
 ('quote', 542),
 ('cho', 517),
 ('được', 504),
 ('một', 500),
 ('visit', 487),
 ('da', 483),
 ('không', 480),
 ('go', 458),
 ('trong', 457),
 ('1', 448),
 ('day', 427),
 ('location', 421),
 ('new', 421),
 ('với', 419),
 ('2017', 414),
 ('second', 413),
 ('camera', 411),
 ('description', 402),
 ('thể', 395),
 ('image', 393),
 ('use', 385),
 ('make', 382),
 ('để', 378),
 ('2', 377),
 ('work', 373),
 ('lifea', 370),
 ('hack', 370),
 ('làm', 370),
 ('những', 359),
 ('share', 342),
 ('3', 336),
 ('amp', 328),
 ('click', 327),
 ('get', 326),
 ('one', 317),
 ('photo', 317),
 ('take', 315),
 ('dụng', 299),
 ('best', 293),
 ('process', 292),
 ('2019', 292),
 ('time', 288),
 ('chất', 287),
 ('e', 285),
 ('like', 280),
 ('công', 276),
 (

In [ ]:
#APPENDING BOTH THE TEXT FEATURES TO CONVERT TO VECTORS OF SIMILIAR SIZES

In [ ]:
Text_features=Text_features.append(test_text_features)

In [ ]:
Text_features

FlickrId  ...                                         Tags_lemma
0      23647573678  ...                                    ifttt instagram
1      23647582078  ...                                    ifttt instagram
2      23647582388  ...                                          instagram
3      23647583748  ...  clothing textile museum aeshm alice amd mary g...
4      23647586378  ...                                    ifttt instagram
...            ...  ...                                                ...
20332  49108928407  ...  phim u1ea3nh chu00faa u0111u1ee9c phu1eadt vu0...
20333  49108930512  ...                                    ifttt instagram
20334  49108933202  ...                                2019 2020 wikipedia
20335  49108933542  ...                                       admin review
20336  49108934937  ...  tacoma tideflats portoftacoma commencementbay ...

[20337 rows x 4 columns]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vector_dsc=TfidfVectorizer(min_df=30)
vector_tit=TfidfVectorizer(min_df=20)
vector_tag=TfidfVectorizer(min_df=10)

In [ ]:
#CONVERTING THE PANDAS INTO NUMPY AND THEN CONVERTING TO NUMERIC
X_tags=Text_features['Tags_lemma'].values
X_desc=Text_features['Description_lemma'].values
X_title=Text_features['Title_lemma'].values

In [ ]:
# #CONVERTING THE PANDAS INTO NUMPY AND THEN CONVERTING TO NUMERIC
# X_test_tags=test_text_features['Tags_lemma'].values
# X_test_desc=test_text_features['Description_lemma'].values
# X_test_title=test_text_features['Title_lemma'].values

In [ ]:
tags_num = vector_tag.fit_transform(X_tags)
print(tags_num.shape)

(20337, 559)


In [ ]:
desc_num = vector_dsc.fit_transform(X_desc)
print(desc_num.shape)

(20337, 353)


In [ ]:
title_num=vector_tit.fit_transform(X_title)
print(title_num.shape)

(20337, 482)


In [ ]:
# test_title_num=vector_tit.fit_transform(X_test_title)
# print(test_title_num.shape)


(20337, 1080)

In [ ]:
#Converting to numpy array
tags_num=tags_num.A
desc_num=desc_num.A
title_num=title_num.A

In [ ]:
title_num.shape

(20337, 482)

In [ ]:
#Breaking it into train and test
train_tags=tags_num[0:20337,:]
test_tags=tags_num[20337:20337+7693,:]

In [ ]:
train_desc=desc_num[0:20337,:]
test_desc=desc_num[20337:20337+7693,:]

In [ ]:
train_tit=title_num[0:20337,:]
test_tit=title_num[20337:20337+7693,:]

In [ ]:
X.shape

(20337, 14)

In [ ]:
# X_final_train=np.hstack((X,train_tit,train_desc,tags_num))

In [ ]:
X_final=np.hstack((X,title_num,desc_num,tags_num))

In [ ]:
X_final.shape

(20337, 1408)

In [ ]:
#FOR 10 times (PAPER)

In [ ]:
#Train and test split 
from sklearn.model_selection import train_test_split
Train_X,Test_X,Train_Y,Test_Y=train_test_split(X_final,Y,test_size=0.1)

In [ ]:
Train_X.shape

(18303, 1408)

In [ ]:
Train_Y

array([28., 22., 28., ..., 12.,  1., 55.])

In [ ]:
X_Train=pd.DataFrame(Train_X) #For the training data for SVR and also for grid search method
# Y_Train=pd.DataFrame(Train_Y) #Dor grid search

In [ ]:
X_Train.to_csv(path_data+'Train_features.csv',index=False)
# Y_Train.to_csv(path_data+'Train_clusters.csv',index=False)

In [ ]:
#Preparing for Random Forest Classifier
from sklearn.ensemble.forest import RandomForestClassifier

In [ ]:
model=RandomForestClassifier(n_estimators=200,criterion='entropy',random_state=42)
model.fit(Train_X[:,1:],Train_Y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [ ]:
from sklearn import metrics

Pred_Y=model.predict(Test_X[:,1:]) 
Pred_Y.shape

(2034,)

In [ ]:
Test_Y

array([ 1.,  1.,  0., ...,  1.,  1., 32.])

In [ ]:
Pred_Y

array([ 0.,  0.,  0., ...,  0.,  0., 32.])

In [ ]:
print(metrics.accuracy_score(Test_Y,Pred_Y))

0.18682399213372664


In [ ]:
#OPTIMISE THE PARAMETERS OF RNF

In [ ]:
#Feature selection using RNF and then allot shapes

In [ ]:
seq_shape

0         1         2         3  ...        26        27        28   29
0   0.404540  0.550014  0.629478  0.681981  ...  0.986112  0.990879  0.995408  1.0
1   0.755823  0.868942  0.911662  0.932169  ...  0.998064  0.998732  0.999293  1.0
2   0.028872  0.038152  0.051010  0.084740  ...  0.997694  0.998145  0.998626  1.0
3   0.008756  0.015012  0.017288  0.021034  ...  0.999697  0.999697  1.000000  1.0
4   0.003812  0.006396  0.008306  0.013330  ...  0.998589  0.999453  0.999878  1.0
5   0.007065  0.007065  0.007065  0.007065  ...  1.000000  1.000000  1.000000  1.0
6   0.002548  0.002991  0.005364  0.006213  ...  1.000000  1.000000  1.000000  1.0
7   0.008736  0.012392  0.012392  0.012392  ...  1.000000  1.000000  1.000000  1.0
8   0.003717  0.005914  0.005914  0.005914  ...  0.997396  0.997465  0.999809  1.0
9   0.000000  0.000506  0.003472  0.003472  ...  1.000000  1.000000  1.000000  1.0
10  0.007696  0.014039  0.014538  0.015420  ...  0.975679  0.984104  0.990779  1.0
11  0.000000  0.000000  0.000000  0.000000  ...  0.996736  0.996736  0.996736  1.0
12  0.000000  0.000000  0.000000  0.000000  ...  1.000000  1.000000  1.000000  1.0
13  0.012236  0.016505  0.017652  0.023319  ...  0.999292  1.000000  1.000000  1.0
14  0.000000  0.000000  0.000000  0.000000  ...  1.000000  1.000000  1.000000  1.0
15  0.006128  0.006656  0.007277  0.011255  ...  0.997086  0.999078  1.000000  1.0
16  0.004167  0.004167  0.004167  0.004167  ...  1.000000  1.000000  1.000000  1.0
17  0.002961  0.003344  0.003344  0.003344  ...  1.000000  1.000000  1.000000  1.0
18  0.000000  0.000000  0.000000  0.000000  ...  1.000000  1.000000  1.000000  1.0
19  0.003075  0.004526  0.008916  0.011303  ...  0.994550  0.994988  0.995383  1.0
20  0.001312  0.003632  0.003632  0.003632  ...  0.003632  0.019223  0.664343  1.0
21  0.000000  0.000000  0.000000  0.000000  ...  1.000000  1.000000  1.000000  1.0
22  0.000000  0.000000  0.000000  0.000000  ...  0.299704  0.939599  0.994836  1.0
23  0.065932  0.108438  0.161203  0.188162  ...  0.737175  0.911178  0.965154  1.0
24  0.039394  0.053434  0.073868  0.074927  ...  0.583170  0.833738  0.954111  1.0
25  0.061027  0.070329  0.086344  0.113370  ...  0.467113  0.538755  0.691146  1.0
26  0.006523  0.008517  0.008517  0.008517  ...  0.751456  0.914141  0.938211  1.0
27  0.021661  0.038661  0.039225  0.043433  ...  0.222892  0.337153  0.879721  1.0
28  0.005814  0.014144  0.017301  0.020472  ...  0.555903  0.713218  0.951997  1.0
29  0.085057  0.109953  0.111913  0.127398  ...  0.987076  0.987794  0.991080  1.0
30  0.000000  0.000000  0.000000  0.000000  ...  0.979592  1.000000  1.000000  1.0
31  0.029551  0.058404  0.089800  0.102683  ...  0.473597  0.486500  0.566075  1.0
32  0.000000  0.000000  0.000000  0.029801  ...  1.000000  1.000000  1.000000  1.0
33  0.000000  0.033784  0.033784  0.033784  ...  0.600140  0.600140  0.724920  1.0
34  0.000000  0.000000  0.000000  0.012887  ...  0.547954  0.569416  0.733840  1.0
35  0.000000  0.000000  0.000000  0.000000  ...  0.630392  0.712310  0.729297  1.0
36  0.000000  0.000000  0.000000  0.000000  ...  0.606821  0.606821  0.606821  1.0
37  0.200000  0.200000  0.200000  0.200000  ...  1.000000  1.000000  1.000000  1.0
38  0.000000  0.000000  0.000000  0.000000  ...  0.833333  0.846213  1.000000  1.0
39  0.000000  0.000000  0.000000  0.000000  ...  0.655890  0.750000  0.750000  1.0
40  0.000000  0.000000  0.000000  0.000000  ...  1.000000  1.000000  1.000000  1.0
41  0.000000  0.000000  0.000000  0.000000  ...  1.000000  1.000000  1.000000  1.0
42  0.000000  0.000000  0.000000  0.000000  ...  0.500000  0.500000  0.900915  1.0
43  0.000000  0.000000  0.000000  0.000000  ...  0.666667  0.666667  1.000000  1.0
44  0.000000  0.000000  0.000000  0.000000  ...  1.000000  1.000000  1.000000  1.0
45  0.000000  0.000000  0.000000  0.000000  ...  0.500000  0.500000  0.500000  1.0
46  0.000000  0.000000  0.000000  0.000000  ...  0.527688  1.000000  1.000000  1.0
47  0.000000  0.000000  0.0

In [ ]:
#The data to be tested on
X_Test=pd.DataFrame(Test_X)

In [ ]:
X_Test

0     1     2      3         4     ...  3175  3176  3177  3178  3179
0     3.749323e+10   0.0   1.0   12.0    6815.0  ...   0.0   0.0   0.0   0.0   0.0
1     3.747584e+10   0.0   0.0  106.0     168.0  ...   0.0   0.0   0.0   0.0   0.0
2     3.679286e+10   0.0   0.0  545.0     332.0  ...   0.0   0.0   0.0   0.0   0.0
3     2.364766e+10   0.0   0.0    1.0    5895.0  ...   0.0   0.0   0.0   0.0   0.0
4     3.686991e+10   0.0   1.0   63.0    1520.0  ...   0.0   0.0   0.0   0.0   0.0
...            ...   ...   ...    ...       ...  ...   ...   ...   ...   ...   ...
2029  4.910509e+10   0.0   0.0  106.0     112.0  ...   0.0   0.0   0.0   0.0   0.0
2030  4.910627e+10   1.0   1.0   15.0  100423.0  ...   0.0   0.0   0.0   0.0   0.0
2031  3.679785e+10   0.0   0.0    0.0     322.0  ...   0.0   0.0   0.0   0.0   0.0
2032  3.753836e+10   1.0   1.0  746.0   25579.0  ...   0.0   0.0   0.0   0.0   0.0
2033  3.679544e+10   0.0   0.0  260.0     523.0  ...   0.0   0.0   0.0   0.0   0.0

[2034 rows x 3180 columns]

In [ ]:
X_Test.to_csv(path_data+'Test_features.csv',index=False)

In [ ]:
#Getting another file with the FlickrId and their shape

In [ ]:
Test_Shapes=pd.DataFrame(Test_X[:,0],columns=['FlickrId'])

In [ ]:
Test_Shapes['Cluster']=Pred_Y

In [ ]:
Test_Shapes

FlickrId  Cluster
0     3.749323e+10      0.0
1     3.747584e+10      0.0
2     3.679286e+10      0.0
3     2.364766e+10      0.0
4     3.686991e+10      0.0
...            ...      ...
2029  4.910509e+10      0.0
2030  4.910627e+10      1.0
2031  3.679785e+10      0.0
2032  3.753836e+10      0.0
2033  3.679544e+10      0.0

[2034 rows x 2 columns]

In [ ]:
seq_shape['Cluster']=seq_shape.index

In [ ]:
seq_shape.head()

0         1         2         3  ...        27        28   29  Cluster
0  0.404540  0.550014  0.629478  0.681981  ...  0.990879  0.995408  1.0        0
1  0.755823  0.868942  0.911662  0.932169  ...  0.998732  0.999293  1.0        1
2  0.028872  0.038152  0.051010  0.084740  ...  0.998145  0.998626  1.0        2
3  0.008756  0.015012  0.017288  0.021034  ...  0.999697  1.000000  1.0        3
4  0.003812  0.006396  0.008306  0.013330  ...  0.999453  0.999878  1.0        4

[5 rows x 31 columns]

In [ ]:
#Merging the two to get flickrids with predicted shapes

In [ ]:
Test_Shape_Data=pd.merge(Test_Shapes,seq_shape,on="Cluster")

In [ ]:
Test_Shape_Data

FlickrId  Cluster         0  ...        27        28   29
0     3.749323e+10      0.0  0.404540  ...  0.990879  0.995408  1.0
1     3.747584e+10      0.0  0.404540  ...  0.990879  0.995408  1.0
2     3.679286e+10      0.0  0.404540  ...  0.990879  0.995408  1.0
3     2.364766e+10      0.0  0.404540  ...  0.990879  0.995408  1.0
4     3.686991e+10      0.0  0.404540  ...  0.990879  0.995408  1.0
...            ...      ...       ...  ...       ...       ...  ...
2029  3.749525e+10     24.0  0.039394  ...  0.833738  0.954111  1.0
2030  3.751210e+10     24.0  0.039394  ...  0.833738  0.954111  1.0
2031  4.910652e+10     30.0  0.000000  ...  1.000000  1.000000  1.0
2032  3.751181e+10     27.0  0.021661  ...  0.337153  0.879721  1.0
2033  3.687183e+10     13.0  0.012236  ...  1.000000  1.000000  1.0

[2034 rows x 32 columns]

In [ ]:
# Test_Shapes[Test_Shapes['Cluster']==32]

In [ ]:
Test_Shape_Data.to_csv(path_data+'Test_Shape_Data.csv',index=False)

In [ ]:
#FOR PREDICTION DATA

In [ ]:
test_features

FlickrId  Ispro  HasStats  ...  NumGroups  AvgGroupsMemb  AvgGroupPhotos
0     49098581833      1         1  ...          0       0.000000    0.000000e+00
1     49098582593      0         0  ...          3     456.000000    1.217800e+04
2     49098582698      1         1  ...         69   41385.347826    2.480120e+06
3     49098582733      1         1  ...          4    2458.250000    7.432825e+04
4     49098584118      0         0  ...          0       0.000000    0.000000e+00
...           ...    ...       ...  ...        ...            ...             ...
7688  49104539732      0         0  ...          0       0.000000    0.000000e+00
7689  49104542697      0         0  ...          6    9716.000000    6.995257e+05
7690  49104544567      0         0  ...          0       0.000000    0.000000e+00
7691  49104545392      1         1  ...          0       0.000000    0.000000e+00
7692  49104546122      0         0  ...          0       0.000000    0.000000e+00

[7693 rows x 14 columns]

In [ ]:
X_prediction=test_features.values
X_prediction.shape

(7693, 14)

In [ ]:
X_final_test=np.hstack((X_prediction,test_tit,test_desc,test_tags))

In [ ]:
X_final_test.shape

(7693, 2248)

In [ ]:
#CLUSTER PREDICTION
Y_prediction=model.predict(X_final_test[:,1:]) 
Y_prediction.shape

(7693,)

In [ ]:
Y_prediction

array([0., 0., 0., ..., 1., 0., 1.])

In [ ]:
#SAVING THE PREDICTION FEATURES
Predcit_features=pd.DataFrame(X_final_test)

In [ ]:
Predcit_features

0     1     2       3       4     ...  3175  3176  3177  3178  3179
0     4.909858e+10   1.0   1.0     1.0  4645.0  ...   0.0   0.0   0.0   0.0   0.0
1     4.909858e+10   0.0   0.0   269.0    65.0  ...   0.0   0.0   0.0   0.0   0.0
2     4.909858e+10   1.0   1.0  1077.0  6338.0  ...   0.0   0.0   0.0   0.0   0.0
3     4.909858e+10   1.0   1.0   101.0  1897.0  ...   0.0   0.0   0.0   0.0   0.0
4     4.909858e+10   0.0   0.0     0.0   273.0  ...   0.0   0.0   0.0   0.0   0.0
...            ...   ...   ...     ...     ...  ...   ...   ...   ...   ...   ...
7688  4.910454e+10   0.0   0.0     0.0   204.0  ...   0.0   0.0   0.0   0.0   0.0
7689  4.910454e+10   0.0   0.0   136.0    15.0  ...   0.0   0.0   0.0   0.0   0.0
7690  4.910454e+10   0.0   0.0     2.0    41.0  ...   0.0   0.0   0.0   0.0   0.0
7691  4.910455e+10   1.0   1.0    18.0  7957.0  ...   0.0   0.0   0.0   0.0   0.0
7692  4.910455e+10   0.0   0.0     0.0   199.0  ...   0.0   0.0   0.0   0.0   0.0

[7693 rows x 3180 columns]

In [ ]:
Predcit_features.to_csv(test_path_data+'Predict_features.csv',index=False)

In [ ]:
#ALLOTING PROTOTYPES TO PREDICTED CLUSTERS
Predicted_Shapes=pd.DataFrame(X_final_test[:,0],columns=['FlickrId'])

In [ ]:
Predicted_Shapes['Cluster']=Y_prediction

In [ ]:
X_final_test[0,0]

49098581833.0

In [ ]:
Predicted_Shapes

FlickrId  Cluster
0     4.909858e+10      0.0
1     4.909858e+10      0.0
2     4.909858e+10      0.0
3     4.909858e+10      0.0
4     4.909858e+10     32.0
...            ...      ...
7688  4.910454e+10      0.0
7689  4.910454e+10      0.0
7690  4.910454e+10      1.0
7691  4.910455e+10      0.0
7692  4.910455e+10      1.0

[7693 rows x 2 columns]

In [ ]:
#ALLOTING SHAPES
Predicted_Shape_Data=pd.merge(Predicted_Shapes,seq_shape,on="Cluster")

In [ ]:
Predicted_Shape_Data

FlickrId  Cluster        0  ...        27        28   29
0     4.909858e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
1     4.909858e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
2     4.909858e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
3     4.909858e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
4     4.909859e+10      0.0  0.40454  ...  0.990879  0.995408  1.0
...            ...      ...      ...  ...       ...       ...  ...
7688  4.910115e+10     18.0  0.00000  ...  1.000000  1.000000  1.0
7689  4.910277e+10     35.0  0.00000  ...  0.712310  0.729297  1.0
7690  4.910295e+10     21.0  0.00000  ...  1.000000  1.000000  1.0
7691  4.910374e+10     21.0  0.00000  ...  1.000000  1.000000  1.0
7692  4.910406e+10     22.0  0.00000  ...  0.939599  0.994836  1.0

[7693 rows x 32 columns]

In [ ]:
Predicted_Shape_Data.to_csv(test_path_data+'Predicted_Shape_Data.csv',index=False)